name: "Check Maven GitFlow Compliance"
description: "Checks whether Maven versioning, GitFlow and SemVer are correctly used"
inputs:
  git-ref:
    description: "The currently checked-out Git reference"
    required: true
    default: ${{ github.ref }}
  git-target-ref:
    description: "The GitHub pull request target Git reference"
    required: false
    default: ${{ github.base_ref }}
  project-version:
    description: "The version of the Maven project"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/check-maven-gitflow.sh "${{ inputs.git-ref }}" "${{ inputs.project-version }}" "${{ inputs.git-target-ref }}"
        [ $? -eq 0 ] || echo "::error ::Maven GitFlow compliance check failed"
      shell: bash
