name: CI Workflow

on: [push, pull_request]

jobs:
  ci-build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Preparation: Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Preparation: Java Setup"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Preparation: Maven Cache"
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: "Preparation: SonarCloud Cache"
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - id: fetch-maven-info
        name: "Preparation: Fetch Maven Info"
        uses: ./.github/actions/fetch-maven-info
      - name: "Preparation: Sanity Check"
        uses: ./.github/actions/check-maven-gitflow
        with:
          git-ref: ${{ github.ref }}
          git-target-ref: ${{ github.base_ref }}
          project-version: ${{ steps.fetch-maven-info.outputs.project-version }}
      - name: "Build: Maven"
        run: >
          mvn -B
          -Dartifact=de.syquel.maven.reactorstate:reactorstate-maven-extension:${{ steps.fetch-maven-info.outputs.project-version }}:jar:shaded
          -Dmdep.stripVersion=true
          verify dependency:copy
      - name: "Build: Maven with Extension" # Let's take our own poison
        run: mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar verify
      - name: "Documentation: Maven Site" # Implicitly tests the extension; without it the inter-module dependencies couldn't be resolved
        run: mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar site
      - name: "Reporting: SonarCloud"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar
          -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=syquel-github -Dsonar.projectKey=Syquel_reactorstate-maven
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: "Deployment: Setup Secrets"
        if: ${{ github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/') }}
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: maven
          server-username: MAVEN_USER
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: "Deployment: Sign Artifacts"
        if: ${{ github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/') }}
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PROJECT_URL: "${{ env.GITHUB_SERVER_URL }}/${{ github.repository }}"
          GIT_URL: "scm:git:git://github.com/${{ github.repository }}.git"
          SSH_URL: "scm:git:ssh://github.com:${{ github.repository }}.git"
        run: >
          mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar
          -Ddist.project.url="${PROJECT_URL}" -Ddist.scm.url="${PROJECT_URL}" -Ddist.scm.connection="${GIT_URL}" -Ddist.scm.developerConnection="${SSH_URL}"
          -Dflatten.mode=ossrh
          flatten:flatten gpg:sign
      - name: "Deployment: GitHub Maven Repository"
        if: ${{ github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/') }}
        env:
          MAVEN_USER: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar
          -DaltDeploymentRepository=maven::https://maven.pkg.github.com/${GITHUB_REPOSITORY} -DdeployAtEnd=true
          deploy:deploy
      - id: deployment-stage-maven-site
        name: "Deployment: Stage Maven Site"
        if: ${{ github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/') }}
        uses: ./.github/actions/stage-maven-site
      - name: "Deployment: GitHub Pages"
        if: ${{ github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: "gh-pages"
          publish_dir: ${{ steps.deployment-stage-maven-site.outputs.staging-directory }}
          destination_dir: "./_mavendocs/${{ steps.fetch-maven-info.outputs.project-version }}"
          allow_empty_commit: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish Maven Site ${{ steps.fetch-maven-info.outputs.project-version }}"
          keep_files: false
          disable_nojekyll: true
      - name: "Deployment: OSSRH Maven Repository"
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          MAVEN_USER: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: >
          mvn -B -Dmaven.ext.class.path=target/dependency/reactorstate-maven-extension-shaded.jar
          -DnexusUrl=https://oss.sonatype.org/ -DserverId=maven -DautoReleaseAfterClose=true
          org.sonatype.plugins:nexus-staging-maven-plugin:deploy
